version: '3'
services:
  keycloak:
    image: quay.io/keycloak/keycloak:16.1.1
    depends_on:
      - auth-db
      - smtp4dev
    environment:
      KEYCLOAK_USER: admin
      KEYCLOAK_PASSWORD: admin
      DB_ADDR: auth-db
      DB_PASSWORD: keycloak
      DB_USER: keycloak
      DB_VENDOR: mariadb
      DB_PORT: 3306
    ports:
      - "8080:8080"
      - "9990:9000"
  auth-db:
    image: mariadb:latest
    environment:
      MYSQL_ROOT_PASSWORD: example
      MYSQL_USER: keycloak
      MYSQL_PASSWORD: keycloak
      MYSQL_DATABASE: keycloak
    volumes:
      - ./keycloak-dev-init.sql:/docker-entrypoint-initdb.d/keycloak-dev-init.sql
  smtp4dev:
    image: rnwood/smtp4dev
    ports:
      - '5000:80'
      - '25:25'
      - '143:143'
